// data.js — vocabulary decks and verb conjugation tables (intermediate level)
// All content is curated so quizzes and conjugation answers are correct.

const VOCAB_DECKS = [
  {
    id: "food",
    name: "Comida y bebida",
    emoji: "🍽️",
    cards: [
      { es: "el desayuno", en: "breakfast" },
      { es: "el almuerzo", en: "lunch" },
      { es: "la cena", en: "dinner" },
      { es: "el aguacate", en: "avocado" },
      { es: "la fresa", en: "strawberry" },
      { es: "el ajo", en: "garlic" },
      { es: "la harina", en: "flour" },
      { es: "el cordero", en: "lamb" },
      { es: "los mariscos", en: "seafood / shellfish" },
      { es: "el pavo", en: "turkey" },
      { es: "agrio", en: "sour" },
      { es: "soso", en: "bland / tasteless" },
      { es: "picante", en: "spicy" },
      { es: "hervir", en: "to boil" },
      { es: "probar", en: "to taste / to try" },
      { es: "la receta", en: "recipe" },
    ],
  },
  {
    id: "travel",
    name: "Viajes",
    emoji: "✈️",
    cards: [
      { es: "el aeropuerto", en: "airport" },
      { es: "la aduana", en: "customs" },
      { es: "el equipaje", en: "luggage" },
      { es: "la maleta", en: "suitcase" },
      { es: "el billete", en: "ticket" },
      { es: "el vuelo", en: "flight" },
      { es: "el retraso", en: "delay" },
      { es: "alojarse", en: "to stay (lodging)" },
      { es: "el alojamiento", en: "accommodation" },
      { es: "la frontera", en: "border" },
      { es: "el paisaje", en: "landscape / scenery" },
      { es: "hacer las maletas", en: "to pack" },
      { es: "el destino", en: "destination" },
      { es: "perderse", en: "to get lost" },
      { es: "el extranjero", en: "abroad / foreigner" },
      { es: "el seguro de viaje", en: "travel insurance" },
    ],
  },
  {
    id: "work",
    name: "Trabajo",
    emoji: "💼",
    cards: [
      { es: "la empresa", en: "company" },
      { es: "el sueldo", en: "salary" },
      { es: "la reunión", en: "meeting" },
      { es: "el jefe", en: "boss" },
      { es: "el plazo", en: "deadline" },
      { es: "contratar", en: "to hire" },
      { es: "despedir", en: "to fire / to dismiss" },
      { es: "el horario", en: "schedule" },
      { es: "la entrevista", en: "interview" },
      { es: "el currículum", en: "résumé / CV" },
      { es: "el desempleo", en: "unemployment" },
      { es: "la formación", en: "training" },
      { es: "el ascenso", en: "promotion" },
      { es: "la jornada", en: "working day" },
      { es: "los gastos", en: "expenses" },
      { es: "la factura", en: "invoice / bill" },
    ],
  },
  {
    id: "emotions",
    name: "Emociones y carácter",
    emoji: "😊",
    cards: [
      { es: "orgulloso", en: "proud" },
      { es: "avergonzado", en: "embarrassed / ashamed" },
      { es: "asustado", en: "scared" },
      { es: "emocionado", en: "excited" },
      { es: "harto", en: "fed up" },
      { es: "celoso", en: "jealous" },
      { es: "amable", en: "kind / friendly" },
      { es: "testarudo", en: "stubborn" },
      { es: "tacaño", en: "stingy" },
      { es: "atrevido", en: "daring / bold" },
      { es: "sensato", en: "sensible" },
      { es: "soportar", en: "to put up with / to bear" },
      { es: "animar", en: "to cheer up / to encourage" },
      { es: "el estado de ánimo", en: "mood" },
      { es: "echar de menos", en: "to miss (someone)" },
      { es: "darse cuenta de", en: "to realize" },
    ],
  },
  {
    id: "city",
    name: "La ciudad",
    emoji: "🏙️",
    cards: [
      { es: "el ayuntamiento", en: "city hall" },
      { es: "el barrio", en: "neighborhood" },
      { es: "la acera", en: "sidewalk" },
      { es: "el cruce", en: "intersection" },
      { es: "el atasco", en: "traffic jam" },
      { es: "la parada", en: "stop (bus/metro)" },
      { es: "la esquina", en: "corner" },
      { es: "el rascacielos", en: "skyscraper" },
      { es: "el peatón", en: "pedestrian" },
      { es: "el alquiler", en: "rent" },
      { es: "la cola", en: "queue / line" },
      { es: "el ruido", en: "noise" },
      { es: "atravesar", en: "to cross" },
      { es: "el semáforo", en: "traffic light" },
      { es: "el casco antiguo", en: "old town" },
      { es: "el cajero automático", en: "ATM" },
    ],
  },
  {
    id: "connectors",
    name: "Conectores útiles",
    emoji: "🔗",
    cards: [
      { es: "sin embargo", en: "however" },
      { es: "por lo tanto", en: "therefore" },
      { es: "aunque", en: "although / even though" },
      { es: "a pesar de", en: "in spite of" },
      { es: "por eso", en: "that's why" },
      { es: "mientras tanto", en: "meanwhile" },
      { es: "en cuanto", en: "as soon as" },
      { es: "por si acaso", en: "just in case" },
      { es: "de hecho", en: "in fact" },
      { es: "o sea", en: "in other words / I mean" },
      { es: "a menudo", en: "often" },
      { es: "de vez en cuando", en: "from time to time" },
      { es: "en seguida", en: "right away" },
      { es: "al fin y al cabo", en: "at the end of the day" },
      { es: "ya que", en: "since / given that" },
      { es: "tan pronto como", en: "as soon as" },
    ],
  },
];

// Pronoun labels for conjugation drills
const PRONOUNS = ["yo", "tú", "él/ella/usted", "nosotros", "vosotros", "ellos/ustedes"];

const TENSES = [
  { id: "presente", name: "Presente" },
  { id: "preterito", name: "Pretérito (indefinido)" },
  { id: "imperfecto", name: "Imperfecto" },
  { id: "futuro", name: "Futuro" },
];

// Each verb: conjugations[tense] = [yo, tú, él, nosotros, vosotros, ellos]
const VERBS = [
  {
    infinitive: "hablar",
    en: "to speak",
    type: "regular -ar",
    conjugations: {
      presente: ["hablo", "hablas", "habla", "hablamos", "habláis", "hablan"],
      preterito: ["hablé", "hablaste", "habló", "hablamos", "hablasteis", "hablaron"],
      imperfecto: ["hablaba", "hablabas", "hablaba", "hablábamos", "hablabais", "hablaban"],
      futuro: ["hablaré", "hablarás", "hablará", "hablaremos", "hablaréis", "hablarán"],
    },
  },
  {
    infinitive: "comer",
    en: "to eat",
    type: "regular -er",
    conjugations: {
      presente: ["como", "comes", "come", "comemos", "coméis", "comen"],
      preterito: ["comí", "comiste", "comió", "comimos", "comisteis", "comieron"],
      imperfecto: ["comía", "comías", "comía", "comíamos", "comíais", "comían"],
      futuro: ["comeré", "comerás", "comerá", "comeremos", "comeréis", "comerán"],
    },
  },
  {
    infinitive: "vivir",
    en: "to live",
    type: "regular -ir",
    conjugations: {
      presente: ["vivo", "vives", "vive", "vivimos", "vivís", "viven"],
      preterito: ["viví", "viviste", "vivió", "vivimos", "vivisteis", "vivieron"],
      imperfecto: ["vivía", "vivías", "vivía", "vivíamos", "vivíais", "vivían"],
      futuro: ["viviré", "vivirás", "vivirá", "viviremos", "viviréis", "vivirán"],
    },
  },
  {
    infinitive: "ser",
    en: "to be (essence)",
    type: "irregular",
    conjugations: {
      presente: ["soy", "eres", "es", "somos", "sois", "son"],
      preterito: ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
      imperfecto: ["era", "eras", "era", "éramos", "erais", "eran"],
      futuro: ["seré", "serás", "será", "seremos", "seréis", "serán"],
    },
  },
  {
    infinitive: "estar",
    en: "to be (state)",
    type: "irregular",
    conjugations: {
      presente: ["estoy", "estás", "está", "estamos", "estáis", "están"],
      preterito: ["estuve", "estuviste", "estuvo", "estuvimos", "estuvisteis", "estuvieron"],
      imperfecto: ["estaba", "estabas", "estaba", "estábamos", "estabais", "estaban"],
      futuro: ["estaré", "estarás", "estará", "estaremos", "estaréis", "estarán"],
    },
  },
  {
    infinitive: "tener",
    en: "to have",
    type: "irregular",
    conjugations: {
      presente: ["tengo", "tienes", "tiene", "tenemos", "tenéis", "tienen"],
      preterito: ["tuve", "tuviste", "tuvo", "tuvimos", "tuvisteis", "tuvieron"],
      imperfecto: ["tenía", "tenías", "tenía", "teníamos", "teníais", "tenían"],
      futuro: ["tendré", "tendrás", "tendrá", "tendremos", "tendréis", "tendrán"],
    },
  },
  {
    infinitive: "hacer",
    en: "to do / to make",
    type: "irregular",
    conjugations: {
      presente: ["hago", "haces", "hace", "hacemos", "hacéis", "hacen"],
      preterito: ["hice", "hiciste", "hizo", "hicimos", "hicisteis", "hicieron"],
      imperfecto: ["hacía", "hacías", "hacía", "hacíamos", "hacíais", "hacían"],
      futuro: ["haré", "harás", "hará", "haremos", "haréis", "harán"],
    },
  },
  {
    infinitive: "ir",
    en: "to go",
    type: "irregular",
    conjugations: {
      presente: ["voy", "vas", "va", "vamos", "vais", "van"],
      preterito: ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
      imperfecto: ["iba", "ibas", "iba", "íbamos", "ibais", "iban"],
      futuro: ["iré", "irás", "irá", "iremos", "iréis", "irán"],
    },
  },
  {
    infinitive: "poder",
    en: "to be able to / can",
    type: "stem-changing",
    conjugations: {
      presente: ["puedo", "puedes", "puede", "podemos", "podéis", "pueden"],
      preterito: ["pude", "pudiste", "pudo", "pudimos", "pudisteis", "pudieron"],
      imperfecto: ["podía", "podías", "podía", "podíamos", "podíais", "podían"],
      futuro: ["podré", "podrás", "podrá", "podremos", "podréis", "podrán"],
    },
  },
  {
    infinitive: "querer",
    en: "to want / to love",
    type: "stem-changing",
    conjugations: {
      presente: ["quiero", "quieres", "quiere", "queremos", "queréis", "quieren"],
      preterito: ["quise", "quisiste", "quiso", "quisimos", "quisisteis", "quisieron"],
      imperfecto: ["quería", "querías", "quería", "queríamos", "queríais", "querían"],
      futuro: ["querré", "querrás", "querrá", "querremos", "querréis", "querrán"],
    },
  },
  {
    infinitive: "decir",
    en: "to say / to tell",
    type: "irregular",
    conjugations: {
      presente: ["digo", "dices", "dice", "decimos", "decís", "dicen"],
      preterito: ["dije", "dijiste", "dijo", "dijimos", "dijisteis", "dijeron"],
      imperfecto: ["decía", "decías", "decía", "decíamos", "decíais", "decían"],
      futuro: ["diré", "dirás", "dirá", "diremos", "diréis", "dirán"],
    },
  },
  {
    infinitive: "venir",
    en: "to come",
    type: "irregular",
    conjugations: {
      presente: ["vengo", "vienes", "viene", "venimos", "venís", "vienen"],
      preterito: ["vine", "viniste", "vino", "vinimos", "vinisteis", "vinieron"],
      imperfecto: ["venía", "venías", "venía", "veníamos", "veníais", "venían"],
      futuro: ["vendré", "vendrás", "vendrá", "vendremos", "vendréis", "vendrán"],
    },
  },
  {
    infinitive: "saber",
    en: "to know (facts)",
    type: "irregular",
    conjugations: {
      presente: ["sé", "sabes", "sabe", "sabemos", "sabéis", "saben"],
      preterito: ["supe", "supiste", "supo", "supimos", "supisteis", "supieron"],
      imperfecto: ["sabía", "sabías", "sabía", "sabíamos", "sabíais", "sabían"],
      futuro: ["sabré", "sabrás", "sabrá", "sabremos", "sabréis", "sabrán"],
    },
  },
  {
    infinitive: "pedir",
    en: "to ask for / to order",
    type: "stem-changing",
    conjugations: {
      presente: ["pido", "pides", "pide", "pedimos", "pedís", "piden"],
      preterito: ["pedí", "pediste", "pidió", "pedimos", "pedisteis", "pidieron"],
      imperfecto: ["pedía", "pedías", "pedía", "pedíamos", "pedíais", "pedían"],
      futuro: ["pediré", "pedirás", "pedirá", "pediremos", "pediréis", "pedirán"],
    },
  },
  {
    infinitive: "dormir",
    en: "to sleep",
    type: "stem-changing",
    conjugations: {
      presente: ["duermo", "duermes", "duerme", "dormimos", "dormís", "duermen"],
      preterito: ["dormí", "dormiste", "durmió", "dormimos", "dormisteis", "durmieron"],
      imperfecto: ["dormía", "dormías", "dormía", "dormíamos", "dormíais", "dormían"],
      futuro: ["dormiré", "dormirás", "dormirá", "dormiremos", "dormiréis", "dormirán"],
    },
  },
  {
    infinitive: "dar",
    en: "to give",
    type: "irregular",
    conjugations: {
      presente: ["doy", "das", "da", "damos", "dais", "dan"],
      preterito: ["di", "diste", "dio", "dimos", "disteis", "dieron"],
      imperfecto: ["daba", "dabas", "daba", "dábamos", "dabais", "daban"],
      futuro: ["daré", "darás", "dará", "daremos", "daréis", "darán"],
    },
  },
];

// Grammar quiz questions (fill-in / multiple choice on usage, not just vocab)
const GRAMMAR_QUESTIONS = [
  {
    prompt: "Ayer ___ al cine con mis amigos.",
    answer: "fui",
    options: ["fui", "voy", "iba", "iré"],
    note: "Preterite of 'ir' for a completed past action ('ayer').",
  },
  {
    prompt: "Cuando era niño, ___ en el parque todos los días.",
    answer: "jugaba",
    options: ["jugué", "jugaba", "juego", "jugaré"],
    note: "Imperfect for habitual past actions ('todos los días').",
  },
  {
    prompt: "Espero que ___ buen tiempo mañana.",
    answer: "haga",
    options: ["hace", "haga", "hará", "hizo"],
    note: "Present subjunctive after 'espero que'.",
  },
  {
    prompt: "Si ___ más dinero, viajaría por el mundo.",
    answer: "tuviera",
    options: ["tengo", "tendré", "tuviera", "tenía"],
    note: "Imperfect subjunctive in a hypothetical 'si' clause with conditional.",
  },
  {
    prompt: "Este libro es más interesante ___ el otro.",
    answer: "que",
    options: ["que", "de", "como", "tan"],
    note: "'más ... que' for comparisons.",
  },
  {
    prompt: "No conozco ___ nadie en esta ciudad.",
    answer: "a",
    options: ["a", "de", "en", "—"],
    note: "Personal 'a' before a person, even 'nadie'.",
  },
  {
    prompt: "¿___ cuánto tiempo vives aquí? — Desde hace dos años.",
    answer: "Desde",
    options: ["Desde", "Hace", "Por", "Para"],
    note: "'¿Desde cuándo...?' asks since when; answered with 'desde hace'.",
  },
  {
    prompt: "Llevo dos horas ___ tu llamada.",
    answer: "esperando",
    options: ["esperar", "esperando", "esperado", "espero"],
    note: "'llevar + gerundio' for ongoing duration.",
  },
  {
    prompt: "Me gusta este café, pero el otro me gusta ___.",
    answer: "más",
    options: ["más", "muy", "tan", "mucho"],
    note: "'más' to express 'more' in preference.",
  },
  {
    prompt: "El examen fue ___ difícil que no aprobó nadie.",
    answer: "tan",
    options: ["tan", "tanto", "más", "muy"],
    note: "'tan + adjetivo + que' for consequence.",
  },
  {
    prompt: "Quiero que me ___ la verdad.",
    answer: "digas",
    options: ["dices", "digas", "dirás", "decías"],
    note: "Present subjunctive after a verb of wishing ('quiero que').",
  },
  {
    prompt: "Hemos ___ toda la tarde.",
    answer: "trabajado",
    options: ["trabajar", "trabajando", "trabajado", "trabajé"],
    note: "Past participle with 'haber' for the present perfect.",
  },
];
