// vocab_core.js — frequency-driven core vocabulary (batch 3).
// Common verbs, abstract nouns, society, school/media, adjectives, colors,
// question words, and money. Curated for accuracy; deduped against other decks.

const CORE_DECKS = [
  {
    id: "verbs-2",
    name: "Verbos frecuentes II",
    emoji: "🗣️",
    cards: [
      { es: "gustar", en: "to like (to be pleasing)" },
      { es: "encantar", en: "to love / to delight" },
      { es: "importar", en: "to matter / to mind" },
      { es: "interesar", en: "to interest" },
      { es: "faltar", en: "to be missing / lacking" },
      { es: "tratar", en: "to try / to treat" },
      { es: "intentar", en: "to attempt" },
      { es: "lograr", en: "to achieve / to manage to" },
      { es: "conseguir", en: "to get / to achieve" },
      { es: "aceptar", en: "to accept" },
      { es: "ofrecer", en: "to offer" },
      { es: "elegir", en: "to choose" },
      { es: "evitar", en: "to avoid" },
      { es: "mejorar", en: "to improve" },
      { es: "aumentar", en: "to increase" },
      { es: "reducir", en: "to reduce" },
      { es: "crecer", en: "to grow" },
      { es: "nacer", en: "to be born" },
      { es: "morir", en: "to die" },
      { es: "matar", en: "to kill" },
      { es: "salvar", en: "to save / to rescue" },
      { es: "romper", en: "to break" },
      { es: "arreglar", en: "to fix / to arrange" },
      { es: "construir", en: "to build" },
      { es: "gastar", en: "to spend" },
      { es: "ahorrar", en: "to save (money/time)" },
      { es: "prestar", en: "to lend" },
      { es: "cobrar", en: "to charge / to collect" },
      { es: "costar", en: "to cost" },
      { es: "valer", en: "to be worth" },
    ],
  },
  {
    id: "verbs-3",
    name: "Verbos frecuentes III",
    emoji: "🔁",
    cards: [
      { es: "cerrar", en: "to close" },
      { es: "parar", en: "to stop" },
      { es: "continuar", en: "to continue" },
      { es: "acabar", en: "to finish / to run out" },
      { es: "comenzar", en: "to begin" },
      { es: "durar", en: "to last" },
      { es: "tardar", en: "to take (time) / to be late" },
      { es: "mover", en: "to move" },
      { es: "llenar", en: "to fill" },
      { es: "añadir", en: "to add" },
      { es: "quitar", en: "to take away / to remove" },
      { es: "devolver", en: "to return (something)" },
      { es: "repetir", en: "to repeat" },
      { es: "olvidar", en: "to forget" },
      { es: "preferir", en: "to prefer" },
      { es: "detener", en: "to stop / to detain" },
      { es: "apoyar", en: "to support" },
      { es: "proteger", en: "to protect" },
      { es: "defender", en: "to defend" },
      { es: "pertenecer", en: "to belong" },
      { es: "depender", en: "to depend" },
      { es: "suceder", en: "to happen" },
      { es: "resultar", en: "to turn out / to result" },
      { es: "ocurrir", en: "to occur / to happen" },
    ],
  },
  {
    id: "nouns-ideas",
    name: "Ideas y vida",
    emoji: "💭",
    cards: [
      { es: "la verdad", en: "truth" },
      { es: "la mentira", en: "lie" },
      { es: "el amor", en: "love" },
      { es: "el miedo", en: "fear" },
      { es: "la suerte", en: "luck" },
      { es: "la fuerza", en: "strength / force" },
      { es: "el poder", en: "power" },
      { es: "la paz", en: "peace" },
      { es: "la guerra", en: "war" },
      { es: "la muerte", en: "death" },
      { es: "la salud", en: "health" },
      { es: "la felicidad", en: "happiness" },
      { es: "la tristeza", en: "sadness" },
      { es: "la libertad", en: "freedom" },
      { es: "la duda", en: "doubt" },
      { es: "la esperanza", en: "hope" },
      { es: "el sueño", en: "dream / sleep" },
      { es: "la mente", en: "mind" },
      { es: "el alma", en: "soul (f.: el alma)" },
      { es: "la memoria", en: "memory" },
      { es: "el recuerdo", en: "memory / souvenir" },
      { es: "el pensamiento", en: "thought" },
      { es: "la opinión", en: "opinion" },
      { es: "el sentimiento", en: "feeling" },
      { es: "la costumbre", en: "habit / custom" },
      { es: "la cultura", en: "culture" },
    ],
  },
  {
    id: "nouns-society",
    name: "Sociedad y trabajo",
    emoji: "🏛️",
    cards: [
      { es: "el gobierno", en: "government" },
      { es: "la ley", en: "law" },
      { es: "el pueblo", en: "town / people" },
      { es: "la sociedad", en: "society" },
      { es: "la política", en: "politics" },
      { es: "el político", en: "politician" },
      { es: "el presidente", en: "president" },
      { es: "el rey", en: "king" },
      { es: "la reina", en: "queen" },
      { es: "el ciudadano", en: "citizen" },
      { es: "el ejército", en: "army" },
      { es: "el soldado", en: "soldier" },
      { es: "la policía", en: "police" },
      { es: "el crimen", en: "crime" },
      { es: "la cárcel", en: "prison / jail" },
      { es: "el juez", en: "judge" },
      { es: "el abogado", en: "lawyer" },
      { es: "el derecho", en: "right / law" },
      { es: "la justicia", en: "justice" },
      { es: "el grupo", en: "group" },
      { es: "la comunidad", en: "community" },
      { es: "la población", en: "population" },
      { es: "el equipo", en: "team / equipment" },
      { es: "el negocio", en: "business" },
      { es: "la organización", en: "organization" },
      { es: "la familia", en: "family" },
    ],
  },
  {
    id: "school-media",
    name: "Educación y medios",
    emoji: "🎓",
    cards: [
      { es: "la escuela", en: "school" },
      { es: "la universidad", en: "university" },
      { es: "el estudiante", en: "student" },
      { es: "el profesor", en: "teacher / professor" },
      { es: "el examen", en: "exam" },
      { es: "la nota", en: "grade / note" },
      { es: "la tarea", en: "homework / task" },
      { es: "el curso", en: "course" },
      { es: "el idioma", en: "language" },
      { es: "la historia", en: "history / story" },
      { es: "la ciencia", en: "science" },
      { es: "las matemáticas", en: "mathematics" },
      { es: "el arte", en: "art" },
      { es: "la música", en: "music" },
      { es: "la película", en: "movie / film" },
      { es: "el programa", en: "program" },
      { es: "las noticias", en: "news" },
      { es: "el periódico", en: "newspaper" },
      { es: "la revista", en: "magazine" },
      { es: "la carta", en: "letter" },
      { es: "la página", en: "page" },
      { es: "el tema", en: "topic / theme" },
      { es: "la imagen", en: "image" },
      { es: "el dibujo", en: "drawing" },
      { es: "la pregunta", en: "question" },
      { es: "la respuesta", en: "answer" },
      { es: "el ejemplo", en: "example" },
    ],
  },
  {
    id: "adjectives-2",
    name: "Adjetivos II",
    emoji: "🎭",
    cards: [
      { es: "diferente", en: "different" },
      { es: "distinto", en: "different / distinct" },
      { es: "igual", en: "equal / the same" },
      { es: "parecido", en: "similar" },
      { es: "propio", en: "own" },
      { es: "principal", en: "main" },
      { es: "general", en: "general" },
      { es: "común", en: "common" },
      { es: "especial", en: "special" },
      { es: "normal", en: "normal" },
      { es: "raro", en: "strange / rare" },
      { es: "extraño", en: "strange" },
      { es: "necesario", en: "necessary" },
      { es: "suficiente", en: "enough / sufficient" },
      { es: "imposible", en: "impossible" },
      { es: "claro", en: "clear / light" },
      { es: "oscuro", en: "dark" },
      { es: "seguro", en: "sure / safe" },
      { es: "peligroso", en: "dangerous" },
      { es: "tranquilo", en: "calm" },
      { es: "nervioso", en: "nervous" },
      { es: "serio", en: "serious" },
      { es: "simpático", en: "nice / friendly" },
      { es: "gracioso", en: "funny" },
      { es: "aburrido", en: "boring / bored" },
      { es: "interesante", en: "interesting" },
      { es: "divertido", en: "fun" },
      { es: "próximo", en: "next" },
      { es: "siguiente", en: "following / next" },
    ],
  },
  {
    id: "adjectives-qualities",
    name: "Cualidades",
    emoji: "✨",
    cards: [
      { es: "cómodo", en: "comfortable" },
      { es: "profundo", en: "deep" },
      { es: "ancho", en: "wide" },
      { es: "estrecho", en: "narrow" },
      { es: "redondo", en: "round" },
      { es: "cuadrado", en: "square" },
      { es: "suave", en: "soft / smooth" },
      { es: "duro", en: "hard / tough" },
      { es: "caliente", en: "hot" },
      { es: "frío", en: "cold" },
      { es: "seco", en: "dry" },
      { es: "mojado", en: "wet" },
      { es: "dulce", en: "sweet" },
      { es: "salado", en: "salty" },
      { es: "amargo", en: "bitter" },
      { es: "ligero", en: "light (weight)" },
      { es: "pesado", en: "heavy" },
      { es: "verdadero", en: "true / real" },
      { es: "falso", en: "false" },
      { es: "cierto", en: "certain / true" },
      { es: "justo", en: "fair / just" },
      { es: "antiguo", en: "ancient / old" },
      { es: "moderno", en: "modern" },
      { es: "actual", en: "current / present" },
      { es: "brillante", en: "bright / brilliant" },
      { es: "tonto", en: "silly / dumb" },
      { es: "inteligente", en: "intelligent" },
      { es: "valiente", en: "brave" },
    ],
  },
  {
    id: "colors",
    name: "Los colores",
    emoji: "🌈",
    cards: [
      { es: "el color", en: "color" },
      { es: "rojo", en: "red" },
      { es: "azul", en: "blue" },
      { es: "verde", en: "green" },
      { es: "amarillo", en: "yellow" },
      { es: "negro", en: "black" },
      { es: "blanco", en: "white" },
      { es: "gris", en: "gray" },
      { es: "marrón", en: "brown" },
      { es: "rosa", en: "pink" },
      { es: "morado", en: "purple" },
      { es: "violeta", en: "violet" },
      { es: "dorado", en: "golden" },
      { es: "plateado", en: "silver" },
      { es: "beige", en: "beige" },
    ],
  },
  {
    id: "questions",
    name: "Preguntas",
    emoji: "❓",
    cards: [
      { es: "qué", en: "what" },
      { es: "quién", en: "who" },
      { es: "cuál", en: "which" },
      { es: "cuándo", en: "when" },
      { es: "dónde", en: "where" },
      { es: "cómo", en: "how" },
      { es: "por qué", en: "why" },
      { es: "para qué", en: "what for" },
      { es: "cuánto", en: "how much" },
      { es: "cuántos", en: "how many" },
      { es: "de quién", en: "whose" },
    ],
  },
  {
    id: "money",
    name: "Comercio y dinero",
    emoji: "💰",
    cards: [
      { es: "el precio", en: "price" },
      { es: "la cuenta", en: "bill / account" },
      { es: "el banco", en: "bank" },
      { es: "la tienda", en: "store / shop" },
      { es: "el mercado", en: "market" },
      { es: "el cliente", en: "customer" },
      { es: "el producto", en: "product" },
      { es: "el servicio", en: "service" },
      { es: "la calidad", en: "quality" },
      { es: "la cantidad", en: "quantity / amount" },
      { es: "el cambio", en: "change" },
      { es: "la tarjeta", en: "card" },
      { es: "el efectivo", en: "cash" },
      { es: "la moneda", en: "coin / currency" },
      { es: "la oferta", en: "offer / sale" },
      { es: "el descuento", en: "discount" },
      { es: "la deuda", en: "debt" },
      { es: "el impuesto", en: "tax" },
      { es: "el presupuesto", en: "budget" },
      { es: "la ganancia", en: "profit / gain" },
      { es: "la pérdida", en: "loss" },
      { es: "la compra", en: "purchase" },
      { es: "la venta", en: "sale" },
      { es: "el número", en: "number" },
    ],
  },
];

if (typeof VOCAB_DECKS !== "undefined") {
  CORE_DECKS.forEach((d) => VOCAB_DECKS.push(d));
}
