// vocab_extra.js — high-frequency vocabulary, appended to VOCAB_DECKS.
// Curated for accuracy (genders, accents). Ordered roughly by usefulness.
// These decks flow automatically into Flashcards and the Quiz.

const FREQUENCY_DECKS = [
  {
    id: "essentials",
    name: "Palabras esenciales",
    emoji: "⭐",
    cards: [
      { es: "pero", en: "but" },
      { es: "porque", en: "because" },
      { es: "cuando", en: "when" },
      { es: "como", en: "like / as / how" },
      { es: "muy", en: "very" },
      { es: "también", en: "also / too" },
      { es: "más", en: "more" },
      { es: "menos", en: "less / fewer" },
      { es: "este", en: "this (m.)" },
      { es: "esta", en: "this (f.)" },
      { es: "ese", en: "that (m.)" },
      { es: "todo", en: "all / everything" },
      { es: "nada", en: "nothing" },
      { es: "algo", en: "something" },
      { es: "alguien", en: "someone" },
      { es: "nadie", en: "no one" },
      { es: "aquí", en: "here" },
      { es: "allí", en: "there" },
      { es: "ahora", en: "now" },
      { es: "después", en: "after / afterwards" },
      { es: "antes", en: "before" },
      { es: "siempre", en: "always" },
      { es: "nunca", en: "never" },
      { es: "hoy", en: "today" },
      { es: "ayer", en: "yesterday" },
      { es: "mañana", en: "tomorrow / morning" },
      { es: "tan", en: "so / as" },
      { es: "mucho", en: "a lot / much" },
      { es: "poco", en: "little / few" },
      { es: "otro", en: "other / another" },
      { es: "mismo", en: "same" },
      { es: "cada", en: "each / every" },
      { es: "entre", en: "between / among" },
      { es: "sobre", en: "on / about" },
      { es: "sin", en: "without" },
      { es: "hasta", en: "until / even" },
      { es: "desde", en: "from / since" },
      { es: "durante", en: "during" },
      { es: "contra", en: "against" },
      { es: "según", en: "according to" },
      { es: "mientras", en: "while" },
      { es: "quizás", en: "maybe / perhaps" },
    ],
  },
  {
    id: "useful-verbs",
    name: "Verbos útiles",
    emoji: "🔤",
    cards: [
      { es: "poner", en: "to put / to place" },
      { es: "salir", en: "to go out / to leave" },
      { es: "seguir", en: "to follow / to keep on" },
      { es: "encontrar", en: "to find" },
      { es: "conocer", en: "to know (a person/place)" },
      { es: "sentir", en: "to feel / to be sorry" },
      { es: "parecer", en: "to seem" },
      { es: "perder", en: "to lose" },
      { es: "entender", en: "to understand" },
      { es: "pensar", en: "to think" },
      { es: "volver", en: "to return / to come back" },
      { es: "contar", en: "to count / to tell" },
      { es: "mostrar", en: "to show" },
      { es: "recordar", en: "to remember" },
      { es: "empezar", en: "to begin" },
      { es: "ganar", en: "to win / to earn" },
      { es: "sentarse", en: "to sit down" },
      { es: "levantarse", en: "to get up" },
      { es: "acostarse", en: "to go to bed" },
      { es: "ducharse", en: "to take a shower" },
      { es: "vestirse", en: "to get dressed" },
      { es: "despertarse", en: "to wake up" },
      { es: "preocuparse", en: "to worry" },
      { es: "divertirse", en: "to have fun" },
      { es: "quejarse", en: "to complain" },
      { es: "reírse", en: "to laugh" },
      { es: "enojarse", en: "to get angry" },
      { es: "mudarse", en: "to move (house)" },
    ],
  },
  {
    id: "common-nouns",
    name: "Sustantivos frecuentes",
    emoji: "📦",
    cards: [
      { es: "el tiempo", en: "time / weather" },
      { es: "el año", en: "year" },
      { es: "el día", en: "day" },
      { es: "la vez", en: "time (occurrence)" },
      { es: "el hombre", en: "man" },
      { es: "la mujer", en: "woman" },
      { es: "la cosa", en: "thing" },
      { es: "la vida", en: "life" },
      { es: "el momento", en: "moment" },
      { es: "la parte", en: "part" },
      { es: "la gente", en: "people" },
      { es: "el mundo", en: "world" },
      { es: "el país", en: "country" },
      { es: "el problema", en: "problem" },
      { es: "la mano", en: "hand" },
      { es: "el lugar", en: "place" },
      { es: "el caso", en: "case" },
      { es: "la palabra", en: "word" },
      { es: "el nombre", en: "name" },
      { es: "la idea", en: "idea" },
      { es: "la calle", en: "street" },
      { es: "el dinero", en: "money" },
      { es: "el libro", en: "book" },
      { es: "la noche", en: "night" },
      { es: "la luz", en: "light" },
      { es: "el agua", en: "water (f.: el agua)" },
      { es: "la casa", en: "house" },
      { es: "la puerta", en: "door" },
      { es: "la ventana", en: "window" },
      { es: "la mesa", en: "table" },
      { es: "la silla", en: "chair" },
      { es: "el coche", en: "car" },
      { es: "la cama", en: "bed" },
      { es: "el papel", en: "paper / role" },
      { es: "la cara", en: "face" },
    ],
  },
  {
    id: "adjectives",
    name: "Adjetivos comunes",
    emoji: "🎨",
    cards: [
      { es: "bueno", en: "good" },
      { es: "malo", en: "bad" },
      { es: "grande", en: "big / large" },
      { es: "pequeño", en: "small" },
      { es: "nuevo", en: "new" },
      { es: "viejo", en: "old" },
      { es: "alto", en: "tall / high" },
      { es: "bajo", en: "short / low" },
      { es: "largo", en: "long" },
      { es: "corto", en: "short (length)" },
      { es: "joven", en: "young" },
      { es: "importante", en: "important" },
      { es: "difícil", en: "difficult" },
      { es: "fácil", en: "easy" },
      { es: "posible", en: "possible" },
      { es: "fuerte", en: "strong" },
      { es: "débil", en: "weak" },
      { es: "rápido", en: "fast" },
      { es: "lento", en: "slow" },
      { es: "caro", en: "expensive" },
      { es: "barato", en: "cheap" },
      { es: "limpio", en: "clean" },
      { es: "sucio", en: "dirty" },
      { es: "lleno", en: "full" },
      { es: "vacío", en: "empty" },
      { es: "rico", en: "rich / tasty" },
      { es: "pobre", en: "poor" },
      { es: "feliz", en: "happy" },
      { es: "triste", en: "sad" },
      { es: "cansado", en: "tired" },
      { es: "enfermo", en: "sick" },
      { es: "sano", en: "healthy" },
      { es: "listo", en: "ready / clever" },
      { es: "ocupado", en: "busy" },
      { es: "libre", en: "free" },
      { es: "hermoso", en: "beautiful" },
      { es: "feo", en: "ugly" },
    ],
  },
  {
    id: "adverbs",
    name: "Adverbios",
    emoji: "🧭",
    cards: [
      { es: "casi", en: "almost" },
      { es: "apenas", en: "barely / hardly" },
      { es: "demasiado", en: "too / too much" },
      { es: "bastante", en: "quite / enough" },
      { es: "así", en: "like this / that way" },
      { es: "despacio", en: "slowly" },
      { es: "pronto", en: "soon" },
      { es: "tarde", en: "late" },
      { es: "temprano", en: "early" },
      { es: "lejos", en: "far" },
      { es: "cerca", en: "near / close" },
      { es: "arriba", en: "up / above" },
      { es: "abajo", en: "down / below" },
      { es: "dentro", en: "inside" },
      { es: "fuera", en: "outside" },
      { es: "adelante", en: "forward / ahead" },
      { es: "atrás", en: "back / behind" },
      { es: "enfrente", en: "opposite / in front" },
      { es: "juntos", en: "together" },
      { es: "solo", en: "only / alone" },
      { es: "realmente", en: "really" },
      { es: "seguramente", en: "surely / probably" },
    ],
  },
  {
    id: "numbers",
    name: "Números",
    emoji: "🔢",
    cards: [
      { es: "cero", en: "zero" },
      { es: "uno", en: "one" },
      { es: "dos", en: "two" },
      { es: "tres", en: "three" },
      { es: "cuatro", en: "four" },
      { es: "cinco", en: "five" },
      { es: "seis", en: "six" },
      { es: "siete", en: "seven" },
      { es: "ocho", en: "eight" },
      { es: "nueve", en: "nine" },
      { es: "diez", en: "ten" },
      { es: "once", en: "eleven" },
      { es: "doce", en: "twelve" },
      { es: "veinte", en: "twenty" },
      { es: "treinta", en: "thirty" },
      { es: "cuarenta", en: "forty" },
      { es: "cincuenta", en: "fifty" },
      { es: "cien", en: "one hundred" },
      { es: "mil", en: "one thousand" },
      { es: "el millón", en: "million" },
      { es: "primero", en: "first" },
      { es: "segundo", en: "second" },
      { es: "último", en: "last" },
    ],
  },
  {
    id: "calendar",
    name: "Días y meses",
    emoji: "📅",
    cards: [
      { es: "el lunes", en: "Monday" },
      { es: "el martes", en: "Tuesday" },
      { es: "el miércoles", en: "Wednesday" },
      { es: "el jueves", en: "Thursday" },
      { es: "el viernes", en: "Friday" },
      { es: "el sábado", en: "Saturday" },
      { es: "el domingo", en: "Sunday" },
      { es: "enero", en: "January" },
      { es: "febrero", en: "February" },
      { es: "marzo", en: "March" },
      { es: "abril", en: "April" },
      { es: "mayo", en: "May" },
      { es: "junio", en: "June" },
      { es: "julio", en: "July" },
      { es: "agosto", en: "August" },
      { es: "septiembre", en: "September" },
      { es: "octubre", en: "October" },
      { es: "noviembre", en: "November" },
      { es: "diciembre", en: "December" },
      { es: "el minuto", en: "minute" },
      { es: "el segundo", en: "second (time)" },
      { es: "el mediodía", en: "noon / midday" },
      { es: "la medianoche", en: "midnight" },
      { es: "el fin de semana", en: "weekend" },
    ],
  },
];

// Append to the master deck list so Flashcards and Quiz pick them up.
if (typeof VOCAB_DECKS !== "undefined") {
  FREQUENCY_DECKS.forEach((d) => VOCAB_DECKS.push(d));
}
