// vocab_extra2.js — thematic vocabulary batch 2, appended to VOCAB_DECKS.
// Curated for accuracy (genders, accents). Everyday concrete vocabulary that
// rounds out the high-frequency core.

const THEMATIC_DECKS_2 = [
  {
    id: "body",
    name: "El cuerpo",
    emoji: "🧍",
    cards: [
      { es: "la cabeza", en: "head" },
      { es: "el pelo", en: "hair" },
      { es: "el ojo", en: "eye" },
      { es: "la oreja", en: "ear" },
      { es: "la nariz", en: "nose" },
      { es: "la boca", en: "mouth" },
      { es: "el diente", en: "tooth" },
      { es: "la lengua", en: "tongue / language" },
      { es: "el cuello", en: "neck" },
      { es: "el hombro", en: "shoulder" },
      { es: "el brazo", en: "arm" },
      { es: "el codo", en: "elbow" },
      { es: "la muñeca", en: "wrist" },
      { es: "el dedo", en: "finger" },
      { es: "la pierna", en: "leg" },
      { es: "la rodilla", en: "knee" },
      { es: "el pie", en: "foot" },
      { es: "el corazón", en: "heart" },
      { es: "el cerebro", en: "brain" },
      { es: "el hueso", en: "bone" },
      { es: "la piel", en: "skin" },
      { es: "la sangre", en: "blood" },
      { es: "el pecho", en: "chest" },
      { es: "la espalda", en: "back" },
      { es: "el estómago", en: "stomach" },
      { es: "la garganta", en: "throat" },
    ],
  },
  {
    id: "home",
    name: "La casa",
    emoji: "🏠",
    cards: [
      { es: "la cocina", en: "kitchen" },
      { es: "el dormitorio", en: "bedroom" },
      { es: "el baño", en: "bathroom" },
      { es: "la sala", en: "living room" },
      { es: "el comedor", en: "dining room" },
      { es: "el pasillo", en: "hallway" },
      { es: "la escalera", en: "stairs" },
      { es: "el techo", en: "ceiling / roof" },
      { es: "el suelo", en: "floor / ground" },
      { es: "la pared", en: "wall" },
      { es: "el jardín", en: "garden / yard" },
      { es: "el garaje", en: "garage" },
      { es: "la llave", en: "key" },
      { es: "el mueble", en: "piece of furniture" },
      { es: "el sofá", en: "sofa / couch" },
      { es: "la nevera", en: "fridge" },
      { es: "el horno", en: "oven" },
      { es: "el fregadero", en: "sink (kitchen)" },
      { es: "el espejo", en: "mirror" },
      { es: "la alfombra", en: "rug / carpet" },
      { es: "la lámpara", en: "lamp" },
      { es: "la cortina", en: "curtain" },
      { es: "el cajón", en: "drawer" },
      { es: "el armario", en: "wardrobe / closet" },
    ],
  },
  {
    id: "clothing",
    name: "La ropa",
    emoji: "👕",
    cards: [
      { es: "la camisa", en: "shirt" },
      { es: "la camiseta", en: "t-shirt" },
      { es: "el pantalón", en: "trousers / pants" },
      { es: "los vaqueros", en: "jeans" },
      { es: "la falda", en: "skirt" },
      { es: "el vestido", en: "dress" },
      { es: "el abrigo", en: "coat" },
      { es: "la chaqueta", en: "jacket" },
      { es: "el suéter", en: "sweater" },
      { es: "los zapatos", en: "shoes" },
      { es: "las botas", en: "boots" },
      { es: "los calcetines", en: "socks" },
      { es: "el sombrero", en: "hat" },
      { es: "la gorra", en: "cap" },
      { es: "la bufanda", en: "scarf" },
      { es: "los guantes", en: "gloves" },
      { es: "el cinturón", en: "belt" },
      { es: "la corbata", en: "tie" },
      { es: "el traje", en: "suit" },
      { es: "el bolso", en: "handbag / purse" },
      { es: "la cartera", en: "wallet" },
      { es: "las gafas", en: "glasses" },
      { es: "el anillo", en: "ring" },
      { es: "el paraguas", en: "umbrella" },
    ],
  },
  {
    id: "family",
    name: "La familia",
    emoji: "👨‍👩‍👧",
    cards: [
      { es: "la madre", en: "mother" },
      { es: "el padre", en: "father" },
      { es: "los padres", en: "parents" },
      { es: "el hijo", en: "son" },
      { es: "la hija", en: "daughter" },
      { es: "el hermano", en: "brother" },
      { es: "la hermana", en: "sister" },
      { es: "el abuelo", en: "grandfather" },
      { es: "la abuela", en: "grandmother" },
      { es: "el tío", en: "uncle" },
      { es: "la tía", en: "aunt" },
      { es: "el primo", en: "cousin (m.)" },
      { es: "la prima", en: "cousin (f.)" },
      { es: "el sobrino", en: "nephew" },
      { es: "la sobrina", en: "niece" },
      { es: "el nieto", en: "grandson" },
      { es: "la nieta", en: "granddaughter" },
      { es: "el marido", en: "husband" },
      { es: "la esposa", en: "wife" },
      { es: "el novio", en: "boyfriend / groom" },
      { es: "la novia", en: "girlfriend / bride" },
      { es: "el suegro", en: "father-in-law" },
      { es: "la suegra", en: "mother-in-law" },
      { es: "el cuñado", en: "brother-in-law" },
    ],
  },
  {
    id: "nature",
    name: "Naturaleza y clima",
    emoji: "🌦️",
    cards: [
      { es: "el sol", en: "sun" },
      { es: "la luna", en: "moon" },
      { es: "la estrella", en: "star" },
      { es: "el cielo", en: "sky" },
      { es: "la nube", en: "cloud" },
      { es: "la lluvia", en: "rain" },
      { es: "la nieve", en: "snow" },
      { es: "el viento", en: "wind" },
      { es: "la tormenta", en: "storm" },
      { es: "el relámpago", en: "lightning" },
      { es: "el árbol", en: "tree" },
      { es: "la flor", en: "flower" },
      { es: "la hoja", en: "leaf / sheet" },
      { es: "la hierba", en: "grass" },
      { es: "la planta", en: "plant" },
      { es: "el río", en: "river" },
      { es: "el lago", en: "lake" },
      { es: "el mar", en: "sea" },
      { es: "la montaña", en: "mountain" },
      { es: "la playa", en: "beach" },
      { es: "el bosque", en: "forest" },
      { es: "el desierto", en: "desert" },
      { es: "la isla", en: "island" },
      { es: "la tierra", en: "earth / land" },
    ],
  },
  {
    id: "animals",
    name: "Los animales",
    emoji: "🐾",
    cards: [
      { es: "el perro", en: "dog" },
      { es: "el gato", en: "cat" },
      { es: "el caballo", en: "horse" },
      { es: "la vaca", en: "cow" },
      { es: "el cerdo", en: "pig" },
      { es: "la oveja", en: "sheep" },
      { es: "la gallina", en: "hen" },
      { es: "el pájaro", en: "bird" },
      { es: "el ratón", en: "mouse" },
      { es: "el conejo", en: "rabbit" },
      { es: "el león", en: "lion" },
      { es: "el tigre", en: "tiger" },
      { es: "el oso", en: "bear" },
      { es: "el elefante", en: "elephant" },
      { es: "el mono", en: "monkey" },
      { es: "la serpiente", en: "snake" },
      { es: "la araña", en: "spider" },
      { es: "la abeja", en: "bee" },
      { es: "la mosca", en: "fly" },
      { es: "la mariposa", en: "butterfly" },
      { es: "el pato", en: "duck" },
      { es: "el lobo", en: "wolf" },
      { es: "el zorro", en: "fox" },
      { es: "la rana", en: "frog" },
    ],
  },
  {
    id: "food2",
    name: "Comida (más)",
    emoji: "🍲",
    cards: [
      { es: "el pan", en: "bread" },
      { es: "el queso", en: "cheese" },
      { es: "la leche", en: "milk" },
      { es: "el huevo", en: "egg" },
      { es: "la mantequilla", en: "butter" },
      { es: "el arroz", en: "rice" },
      { es: "la pasta", en: "pasta" },
      { es: "la carne", en: "meat" },
      { es: "el pollo", en: "chicken" },
      { es: "la fruta", en: "fruit" },
      { es: "la manzana", en: "apple" },
      { es: "la naranja", en: "orange" },
      { es: "el plátano", en: "banana" },
      { es: "la uva", en: "grape" },
      { es: "el tomate", en: "tomato" },
      { es: "la cebolla", en: "onion" },
      { es: "la zanahoria", en: "carrot" },
      { es: "la lechuga", en: "lettuce" },
      { es: "el azúcar", en: "sugar" },
      { es: "la sal", en: "salt" },
      { es: "el aceite", en: "oil" },
      { es: "el café", en: "coffee" },
      { es: "el vino", en: "wine" },
      { es: "el postre", en: "dessert" },
    ],
  },
  {
    id: "health",
    name: "La salud",
    emoji: "🏥",
    cards: [
      { es: "el médico", en: "doctor" },
      { es: "la enfermera", en: "nurse" },
      { es: "el hospital", en: "hospital" },
      { es: "la farmacia", en: "pharmacy" },
      { es: "la medicina", en: "medicine" },
      { es: "la pastilla", en: "pill" },
      { es: "la receta médica", en: "prescription" },
      { es: "la enfermedad", en: "illness" },
      { es: "el dolor", en: "pain" },
      { es: "la fiebre", en: "fever" },
      { es: "la tos", en: "cough" },
      { es: "el resfriado", en: "cold (illness)" },
      { es: "la gripe", en: "flu" },
      { es: "la herida", en: "wound / injury" },
      { es: "la cita", en: "appointment" },
      { es: "el dentista", en: "dentist" },
      { es: "la vacuna", en: "vaccine" },
      { es: "el síntoma", en: "symptom" },
      { es: "curar", en: "to cure / to heal" },
      { es: "doler", en: "to hurt" },
      { es: "toser", en: "to cough" },
      { es: "respirar", en: "to breathe" },
    ],
  },
  {
    id: "tech",
    name: "Tecnología",
    emoji: "💻",
    cards: [
      { es: "el móvil", en: "cell phone" },
      { es: "la aplicación", en: "app / application" },
      { es: "el correo electrónico", en: "email" },
      { es: "la contraseña", en: "password" },
      { es: "el archivo", en: "file" },
      { es: "la carpeta", en: "folder" },
      { es: "la red", en: "network" },
      { es: "el internet", en: "internet" },
      { es: "la cámara", en: "camera" },
      { es: "la batería", en: "battery" },
      { es: "el cargador", en: "charger" },
      { es: "la impresora", en: "printer" },
      { es: "el teclado", en: "keyboard" },
      { es: "la pantalla", en: "screen" },
      { es: "el botón", en: "button" },
      { es: "el enlace", en: "link" },
      { es: "el mensaje", en: "message" },
      { es: "la llamada", en: "call" },
      { es: "descargar", en: "to download" },
      { es: "guardar", en: "to save" },
      { es: "borrar", en: "to delete / erase" },
      { es: "encender", en: "to turn on" },
      { es: "apagar", en: "to turn off" },
    ],
  },
  {
    id: "transport",
    name: "Transporte",
    emoji: "🚗",
    cards: [
      { es: "el autobús", en: "bus" },
      { es: "el tren", en: "train" },
      { es: "el metro", en: "subway / metro" },
      { es: "el avión", en: "airplane" },
      { es: "el barco", en: "boat / ship" },
      { es: "la bicicleta", en: "bicycle" },
      { es: "la moto", en: "motorcycle" },
      { es: "el taxi", en: "taxi" },
      { es: "el camión", en: "truck" },
      { es: "la estación", en: "station" },
      { es: "el conductor", en: "driver" },
      { es: "el pasajero", en: "passenger" },
      { es: "el camino", en: "road / way" },
      { es: "la carretera", en: "highway" },
      { es: "el puente", en: "bridge" },
      { es: "la gasolina", en: "gasoline" },
      { es: "el mapa", en: "map" },
      { es: "el asiento", en: "seat" },
      { es: "la rueda", en: "wheel" },
      { es: "el motor", en: "engine" },
      { es: "conducir", en: "to drive" },
      { es: "aparcar", en: "to park" },
    ],
  },
];

if (typeof VOCAB_DECKS !== "undefined") {
  THEMATIC_DECKS_2.forEach((d) => VOCAB_DECKS.push(d));
}
